seed_checkpoint_dir = "./demo/seed/longcat"
save_preview_dir = "./demo/inference_longcat_t2i_preview"

hsdp_shard_dim = 1

[model]
arch = "longcat"
type = "base"

[dataset]
type = "pickle_directory"
path = "./demo/preprocess_longcat_t2i"

[sampler]
type = "shifted_euler"
steps = 50
cfg_scale = 4.0
enable_cfg_renorm = true

[processor]
task = "t2i"
preset = "longcat_image"

[launch]
type = "inference"
devices = 4