seed_checkpoint_dir = "./demo/seed/qwen"
save_preview_dir = "./demo/inference_qwen_t2i_preview"

hsdp_shard_dim = 1

[model]
arch = "qwen"
type = "base"

[dataset]
type = "pickle_directory"
path = "./demo/preprocess_qwen_t2i"

[sampler]
type = "shifted_euler"
steps = 28
max_image_seq_len = 8192
max_shift = 0.9
cfg_scale = 4.0
enable_cfg_renorm = true

[processor]
task = "t2i"
preset = "qwen_image"

[launch]
type = "inference"
devices = 4